"""empty message

Revision ID: 3465e7b42922
Revises: 15f0f4468629
Create Date: 2021-01-12 13:57:35.874048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3465e7b42922'
down_revision = '15f0f4468629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('post', sa.Column('poster_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'user', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'poster_id')
    op.drop_column('post', 'created_date')
    # ### end Alembic commands ###
