"""empty message

Revision ID: ecafdd462780
Revises: 3465e7b42922
Create Date: 2021-01-12 14:04:12.837717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecafdd462780'
down_revision = '3465e7b42922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(), nullable=False))
    op.add_column('post', sa.Column('climbing_route', sa.String(), nullable=False))
    op.add_column('post', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('post', 'password')
    op.drop_column('post', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post', 'title')
    op.drop_column('post', 'climbing_route')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
